"""SQLAlchemy ORM models. Import this package everywhere (incl. Alembic)."""

from app.db.session import Base
from app.models.ai import AIEvent, AIMessage, AISession
from app.models.appointment import Appointment
from app.models.consent import Consent
from app.models.emergency import EmergencyContact, EmergencyEvent
from app.models.family import FamilyAccessConsent, FamilyRelationship
from app.models.healthcare import ProviderSpecialty, Specialty, SpecialtyService
from app.models.ops import AuditLog, FeatureFlag, SystemSetting
from app.models.partner import (
    Organization,
    OrganizationMember,
    PartnerClaim,
    PartnerClaimEvent,
    PartnerCommission,
    PartnerDocument,
    PartnerInsuranceClaimDetail,
    PartnerInsurancePolicy,
    PartnerInsuranceProduct,
    PartnerIntegration,
    PartnerLabBooking,
    PartnerLabTest,
    PartnerLifecycleEvent,
    PartnerNotification,
    PartnerProfile,
    PartnerService,
    PartnerSettlement,
    PartnerWebhookEvent,
)
from app.models.pharmacy import (
    Medicine,
    MedicineAlias,
    MedicineOrder,
    MedicineOrderItem,
    MedicinePrice,
    MedicinePriceHistory,
    Pharmacy,
    PharmacyInventory,
    PharmacyVerification,
    PrescriptionRequest,
)
from app.models.providers import (
    Doctor,
    DoctorVerification,
    Hospital,
    HospitalVerification,
    ProviderBlock,
    ProviderService,
    ProviderSpecialtyLink,
    ServiceAvailability,
    ServicePrice,
)
from app.models.user import FamilyMember, Permission, Role, User, UserRole
from app.models.vault import (
    HealthRecord,
    HealthRecordAccessEvent,
    HealthRecordShare,
    StoredFile,
)

__all__ = [
    "AIMessage",
    "AIEvent",
    "AISession",
    "Appointment",
    "AuditLog",
    "Base",
    "Consent",
    "Doctor",
    "DoctorVerification",
    "EmergencyContact",
    "EmergencyEvent",
    "FamilyAccessConsent",
    "FamilyMember",
    "FamilyRelationship",
    "FeatureFlag",
    "HealthRecord",
    "HealthRecordAccessEvent",
    "HealthRecordShare",
    "Hospital",
    "HospitalVerification",
    "Medicine",
    "MedicineAlias",
    "MedicineOrder",
    "MedicineOrderItem",
    "MedicinePrice",
    "MedicinePriceHistory",
    "Organization",
    "OrganizationMember",
    "PartnerClaim",
    "PartnerClaimEvent",
    "PartnerCommission",
    "PartnerDocument",
    "PartnerInsuranceClaimDetail",
    "PartnerInsurancePolicy",
    "PartnerInsuranceProduct",
    "PartnerIntegration",
    "PartnerLabBooking",
    "PartnerLabTest",
    "PartnerLifecycleEvent",
    "PartnerNotification",
    "PartnerProfile",
    "PartnerService",
    "PartnerSettlement",
    "PartnerWebhookEvent",
    "Permission",
    "Pharmacy",
    "PharmacyInventory",
    "PharmacyVerification",
    "PrescriptionRequest",
    "ProviderBlock",
    "ProviderService",
    "ProviderSpecialty",
    "ProviderSpecialtyLink",
    "Role",
    "ServiceAvailability",
    "ServicePrice",
    "Specialty",
    "SpecialtyService",
    "SystemSetting",
    "StoredFile",
    "User",
    "UserRole",
]
