-- PostgreSQL foundation: production migrations should split these domains by module.
CREATE TYPE verification_status AS ENUM ('verified','provider_supplied','user_supplied','estimated','ai_generated');
CREATE TYPE appointment_status AS ENUM ('requested','confirmed','checked_in','in_consultation','completed','cancelled','rejected','no_show','rescheduled');
CREATE TYPE consent_status AS ENUM ('active','revoked','expired');
CREATE TABLE users (id uuid PRIMARY KEY, email text UNIQUE, phone text UNIQUE, password_hash text, role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE patients (id uuid PRIMARY KEY, user_id uuid NOT NULL UNIQUE REFERENCES users(id), full_name text NOT NULL, preferred_language text NOT NULL DEFAULT 'en', blood_group text, allergies jsonb NOT NULL DEFAULT '[]', conditions jsonb NOT NULL DEFAULT '[]', emergency_profile jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE providers (id uuid PRIMARY KEY, kind text NOT NULL CHECK (kind IN ('doctor','hospital','ambulance','lab')), name text NOT NULL, location jsonb, verification verification_status NOT NULL, source_url text, last_verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE appointments (id uuid PRIMARY KEY, patient_id uuid NOT NULL REFERENCES patients(id), provider_id uuid NOT NULL REFERENCES providers(id), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, status appointment_status NOT NULL DEFAULT 'requested', created_at timestamptz NOT NULL DEFAULT now(), CHECK (ends_at > starts_at));
CREATE UNIQUE INDEX appointments_active_slot ON appointments(provider_id, starts_at) WHERE status NOT IN ('cancelled','rejected','rescheduled');
CREATE TABLE documents (id uuid PRIMARY KEY, patient_id uuid NOT NULL REFERENCES patients(id), type text NOT NULL, object_key text NOT NULL, source text, occurred_on date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE consents (id uuid PRIMARY KEY, patient_id uuid NOT NULL REFERENCES patients(id), recipient_user_id uuid NOT NULL REFERENCES users(id), scopes jsonb NOT NULL, status consent_status NOT NULL DEFAULT 'active', starts_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK (expires_at > starts_at));
CREATE TABLE audit_logs (id uuid PRIMARY KEY, actor_user_id uuid REFERENCES users(id), patient_id uuid REFERENCES patients(id), action text NOT NULL, resource_type text NOT NULL, resource_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_logs_patient_created ON audit_logs(patient_id, created_at DESC);
