"""phase 5 health vault

Revision ID: 00e49dc73a52
Revises: 2a34b8868e53
Create Date: 2026-09-19 21:55:37.899399

"""
import sqlalchemy as sa

from alembic import op

revision = '00e49dc73a52'
down_revision = '2a34b8868e53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_record_access_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_record_access_events'))
    )
    with op.batch_alter_table('health_record_access_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_record_access_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_record_access_events_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_record_access_events_record_id'), ['record_id'], unique=False)
        batch_op.create_index('ix_vault_events_actor', ['actor_user_id'], unique=False)
        batch_op.create_index('ix_vault_events_record', ['record_id'], unique=False)

    op.create_table('stored_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('encryption_metadata', sa.Text(), nullable=False),
    sa.Column('upload_status', sa.String(length=20), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_stored_files_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('storage_provider', 'object_key', name='uq_stored_file_object')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index('ix_stored_files_owner', ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_upload_status'), ['upload_status'], unique=False)

    op.create_table('health_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('record_date', sa.String(length=10), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_health_records_created_by_users')),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], name=op.f('fk_health_records_file_id_stored_files')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_health_records_hospital_id_hospitals')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_health_records_patient_id_users')),
    sa.ForeignKeyConstraint(['provider_id'], ['doctors.id'], name=op.f('fk_health_records_provider_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_records'))
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_category'), ['category'], unique=False)
        batch_op.create_index('ix_health_records_dates', ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index('ix_health_records_patient_cat', ['patient_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_status'), ['status'], unique=False)

    op.create_table('health_record_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('consent_id', sa.String(length=36), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('grantee_user_id', sa.String(length=36), nullable=False),
    sa.Column('grantee_type', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('category_filter', sa.String(length=400), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], name=op.f('fk_health_record_shares_consent_id_consents')),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_health_record_shares_granted_by_users')),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], name=op.f('fk_health_record_shares_grantee_user_id_users')),
    sa.ForeignKeyConstraint(['record_id'], ['health_records.id'], name=op.f('fk_health_record_shares_record_id_health_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_record_shares'))
    )
    with op.batch_alter_table('health_record_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_record_shares_grantee_user_id'), ['grantee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_record_shares_record_id'), ['record_id'], unique=False)
        batch_op.create_index('ix_shares_grantee_active', ['grantee_user_id', 'revoked_at'], unique=False)
        batch_op.create_index('ix_shares_record', ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record_shares', schema=None) as batch_op:
        batch_op.drop_index('ix_shares_record')
        batch_op.drop_index('ix_shares_grantee_active')
        batch_op.drop_index(batch_op.f('ix_health_record_shares_record_id'))
        batch_op.drop_index(batch_op.f('ix_health_record_shares_grantee_user_id'))

    op.drop_table('health_record_shares')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_records_status'))
        batch_op.drop_index(batch_op.f('ix_health_records_provider_id'))
        batch_op.drop_index(batch_op.f('ix_health_records_patient_id'))
        batch_op.drop_index('ix_health_records_patient_cat')
        batch_op.drop_index(batch_op.f('ix_health_records_hospital_id'))
        batch_op.drop_index('ix_health_records_dates')
        batch_op.drop_index(batch_op.f('ix_health_records_category'))

    op.drop_table('health_records')
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_upload_status'))
        batch_op.drop_index(batch_op.f('ix_stored_files_owner_id'))
        batch_op.drop_index('ix_stored_files_owner')

    op.drop_table('stored_files')
    with op.batch_alter_table('health_record_access_events', schema=None) as batch_op:
        batch_op.drop_index('ix_vault_events_record')
        batch_op.drop_index('ix_vault_events_actor')
        batch_op.drop_index(batch_op.f('ix_health_record_access_events_record_id'))
        batch_op.drop_index(batch_op.f('ix_health_record_access_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_health_record_access_events_created_at'))

    op.drop_table('health_record_access_events')
    # ### end Alembic commands ###
