"""phase 4 medicines pharmacies prices orders

Revision ID: 2a34b8868e53
Revises: ffff2f1bd46e
Create Date: 2026-09-19 20:02:14.944424

"""
import sqlalchemy as sa

from alembic import op

revision = '2a34b8868e53'
down_revision = 'ffff2f1bd46e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=80), nullable=False),
    sa.Column('dosage_form', sa.String(length=20), nullable=False),
    sa.Column('pack_size', sa.String(length=80), nullable=False),
    sa.Column('prescription_required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active_ingredients', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicines'))
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_generic_name'), ['generic_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_manufacturer'), ['manufacturer'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_prescription_required'), ['prescription_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_status'), ['status'], unique=False)

    op.create_table('medicine_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_kind', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_medicine_aliases_medicine_id_medicines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_aliases'))
    )
    with op.batch_alter_table('medicine_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_aliases_alias', ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_aliases_medicine_id'), ['medicine_id'], unique=False)

    op.create_table('pharmacies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=80), nullable=False),
    sa.Column('license_authority', sa.String(length=120), nullable=False),
    sa.Column('address_line', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.String(length=24), nullable=True),
    sa.Column('longitude', sa.String(length=24), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('operating_hours', sa.Text(), nullable=False),
    sa.Column('delivery_supported', sa.Boolean(), nullable=False),
    sa.Column('pickup_supported', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_pharmacies_admin_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacies'))
    )
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacies_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_delivery_supported'), ['delivery_supported'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_pickup_supported'), ['pickup_supported'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_verification_status'), ['verification_status'], unique=False)

    op.create_table('medicine_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('pickup_option', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_medicine_orders_patient_id_users')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_medicine_orders_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_orders'))
    )
    with op.batch_alter_table('medicine_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_orders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_orders_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_orders_status'), ['status'], unique=False)
        batch_op.create_index('ix_orders_patient_status', ['patient_id', 'status'], unique=False)

    op.create_table('medicine_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_medicine_prices_medicine_id_medicines')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_medicine_prices_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_medicine_prices_verified_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_prices'))
    )
    with op.batch_alter_table('medicine_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_prices_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_prices_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_prices_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_prices_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index('ix_prices_medicine_status', ['medicine_id', 'verification_status'], unique=False)
        batch_op.create_index('ix_prices_pharmacy', ['pharmacy_id'], unique=False)

    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('stock_status', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_pharmacy_inventory_medicine_id_medicines')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_pharmacy_inventory_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_inventory')),
    sa.UniqueConstraint('pharmacy_id', 'medicine_id', name='uq_inventory_pharmacy_medicine')
    )
    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_medicine_stock', ['medicine_id', 'stock_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_inventory_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_inventory_pharmacy_id'), ['pharmacy_id'], unique=False)

    op.create_table('pharmacy_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('document_refs', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_pharmacy_verifications_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_pharmacy_verifications_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_verifications'))
    )
    with op.batch_alter_table('pharmacy_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_verifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_verifications_pharmacy_id'), ['pharmacy_id'], unique=False)

    op.create_table('medicine_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_source', sa.String(length=120), nullable=False),
    sa.Column('price_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_verification_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_medicine_order_items_medicine_id_medicines')),
    sa.ForeignKeyConstraint(['order_id'], ['medicine_orders.id'], name=op.f('fk_medicine_order_items_order_id_medicine_orders')),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['medicine_prices.id'], name=op.f('fk_medicine_order_items_price_snapshot_id_medicine_prices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_order_items'))
    )
    with op.batch_alter_table('medicine_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_order_items_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('medicine_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('price_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_medicine_price_history_actor_user_id_users')),
    sa.ForeignKeyConstraint(['price_id'], ['medicine_prices.id'], name=op.f('fk_medicine_price_history_price_id_medicine_prices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_price_history'))
    )
    with op.batch_alter_table('medicine_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_price_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_price_history_price_id'), ['price_id'], unique=False)
        batch_op.create_index('ix_price_history_price', ['price_id'], unique=False)

    op.create_table('prescription_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('document_ref', sa.String(length=255), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['medicine_orders.id'], name=op.f('fk_prescription_requests_order_id_medicine_orders')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_prescription_requests_patient_id_users')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_prescription_requests_reviewed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_requests'))
    )
    with op.batch_alter_table('prescription_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_requests_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_requests_order_id'))

    op.drop_table('prescription_requests')
    with op.batch_alter_table('medicine_price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_price')
        batch_op.drop_index(batch_op.f('ix_medicine_price_history_price_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_price_history_created_at'))

    op.drop_table('medicine_price_history')
    with op.batch_alter_table('medicine_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_order_items_medicine_id'))

    op.drop_table('medicine_order_items')
    with op.batch_alter_table('pharmacy_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_verifications_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_verifications_created_at'))

    op.drop_table('pharmacy_verifications')
    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_inventory_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_inventory_medicine_id'))
        batch_op.drop_index('ix_inventory_medicine_stock')

    op.drop_table('pharmacy_inventory')
    with op.batch_alter_table('medicine_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_prices_pharmacy')
        batch_op.drop_index('ix_prices_medicine_status')
        batch_op.drop_index(batch_op.f('ix_medicine_prices_verification_status'))
        batch_op.drop_index(batch_op.f('ix_medicine_prices_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_prices_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_prices_is_current'))

    op.drop_table('medicine_prices')
    with op.batch_alter_table('medicine_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_patient_status')
        batch_op.drop_index(batch_op.f('ix_medicine_orders_status'))
        batch_op.drop_index(batch_op.f('ix_medicine_orders_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_orders_patient_id'))

    op.drop_table('medicine_orders')
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacies_verification_status'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_state'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_postal_code'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_pickup_supported'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_delivery_supported'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_city'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_admin_user_id'))

    op.drop_table('pharmacies')
    with op.batch_alter_table('medicine_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_aliases_medicine_id'))
        batch_op.drop_index('ix_aliases_alias')

    op.drop_table('medicine_aliases')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_status'))
        batch_op.drop_index(batch_op.f('ix_medicines_prescription_required'))
        batch_op.drop_index(batch_op.f('ix_medicines_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_medicines_generic_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_brand_name'))

    op.drop_table('medicines')
    # ### end Alembic commands ###
