"""initial core tables

Revision ID: c916d59c142b
Revises: 
Create Date: 2026-09-19 08:45:43.058424

"""
import sqlalchemy as sa

from alembic import op

revision = 'c916d59c142b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_events'))
    )
    with op.batch_alter_table('ai_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_feature_flags'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_te', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties'))
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_slug'), ['slug'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('primary_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_sessions'))
    )
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('data_scope', sa.String(length=200), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('relationship', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_contacts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_contacts'))
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('emergency_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('latitude', sa.String(length=24), nullable=True),
    sa.Column('longitude', sa.String(length=24), nullable=True),
    sa.Column('location_accuracy_m', sa.String(length=16), nullable=True),
    sa.Column('confirmed_by_provider', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_events'))
    )
    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_events_user_id'), ['user_id'], unique=False)

    op.create_table('family_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('relationship', sa.String(length=40), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_family_members_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_members'))
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('provider_specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('specialty_id', sa.String(length=36), nullable=False),
    sa.Column('provider_kind', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_provider_specialties_specialty_id_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_specialties'))
    )
    with op.batch_alter_table('provider_specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_specialties_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_specialties_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('permission_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('specialty_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('specialty_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_te', sa.String(length=160), nullable=False),
    sa.Column('name_hi', sa.String(length=160), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_specialty_services_specialty_id_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialty_services')),
    sa.UniqueConstraint('specialty_id', 'code', name='uq_specialty_service_code')
    )
    with op.batch_alter_table('specialty_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialty_services_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('safety_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], name=op.f('fk_ai_messages_session_id_ai_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_session_id'))

    op.drop_table('ai_messages')
    op.drop_table('user_roles')
    with op.batch_alter_table('specialty_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialty_services_specialty_id'))

    op.drop_table('specialty_services')
    op.drop_table('role_permissions')
    with op.batch_alter_table('provider_specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_specialties_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_provider_specialties_provider_id'))

    op.drop_table('provider_specialties')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_owner_user_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_events_status'))

    op.drop_table('emergency_events')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_user_id'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_consents_consent_type'))

    op.drop_table('consents')
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_sessions_user_id'))

    op.drop_table('ai_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_settings')
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_slug'))

    op.drop_table('specialties')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('feature_flags')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_events_event_type'))

    op.drop_table('ai_events')
    # ### end Alembic commands ###
