"""phase 3 providers and appointments

Revision ID: ffff2f1bd46e
Revises: c916d59c142b
Create Date: 2026-09-19 10:02:37.780277

"""
import sqlalchemy as sa

from alembic import op

revision = 'ffff2f1bd46e'
down_revision = 'c916d59c142b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_kind', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('block_date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_blocks'))
    )
    with op.batch_alter_table('provider_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_provider_blocks_provider', ['provider_kind', 'provider_id', 'block_date'], unique=False)

    op.create_table('service_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_kind', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_availability')),
    sa.UniqueConstraint('provider_kind', 'provider_id', 'weekday', 'start_time', name='uq_availability_rule')
    )
    with op.batch_alter_table('service_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_availability_provider_id'), ['provider_id'], unique=False)

    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hospital_type', sa.String(length=40), nullable=False),
    sa.Column('registration_number', sa.String(length=80), nullable=False),
    sa.Column('address_line', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.String(length=24), nullable=True),
    sa.Column('longitude', sa.String(length=24), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('departments', sa.Text(), nullable=False),
    sa.Column('services_summary', sa.Text(), nullable=False),
    sa.Column('emergency_available', sa.Boolean(), nullable=False),
    sa.Column('emergency_verified', sa.Boolean(), nullable=False),
    sa.Column('insurance_info', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_hospitals_admin_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitals'))
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_pincode'), ['pincode'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_verification_status'), ['verification_status'], unique=False)

    op.create_table('provider_specialty_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_kind', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('specialty_slug', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialty_slug'], ['specialties.slug'], name=op.f('fk_provider_specialty_links_specialty_slug_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_specialty_links')),
    sa.UniqueConstraint('provider_kind', 'provider_id', 'specialty_slug', name='uq_provider_specialty')
    )
    with op.batch_alter_table('provider_specialty_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_specialty_links_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_specialty_links_specialty_slug'), ['specialty_slug'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('specialty_slug', sa.String(length=60), nullable=False),
    sa.Column('sub_specialty', sa.String(length=160), nullable=True),
    sa.Column('qualifications', sa.String(length=300), nullable=False),
    sa.Column('registration_number', sa.String(length=80), nullable=False),
    sa.Column('registration_council', sa.String(length=120), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('languages', sa.String(length=200), nullable=False),
    sa.Column('consultation_modes', sa.String(length=60), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address_line', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.String(length=24), nullable=True),
    sa.Column('longitude', sa.String(length=24), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_doctors_hospital_id_hospitals')),
    sa.ForeignKeyConstraint(['specialty_slug'], ['specialties.slug'], name=op.f('fk_doctors_specialty_slug_specialties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors'))
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_pincode'), ['pincode'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty_slug'), ['specialty_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_verification_status'), ['verification_status'], unique=False)

    op.create_table('hospital_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('document_refs', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_hospital_verifications_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_hospital_verifications_hospital_id_hospitals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospital_verifications'))
    )
    with op.batch_alter_table('hospital_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_verifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_verifications_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('doctor_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('document_refs', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_doctor_verifications_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_doctor_verifications_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_verifications'))
    )
    with op.batch_alter_table('doctor_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_verifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_verifications_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('provider_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_kind', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('specialty_slug', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_te', sa.String(length=160), nullable=False),
    sa.Column('name_hi', sa.String(length=160), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('consultation_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_provider_services_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['specialty_slug'], ['specialties.slug'], name=op.f('fk_provider_services_specialty_slug_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_services'))
    )
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.create_index('ix_provider_services_provider', ['provider_kind', 'provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_services_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_services_specialty_slug'), ['specialty_slug'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('specialty_slug', sa.String(length=60), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_date', sa.String(length=10), nullable=False),
    sa.Column('appointment_time', sa.String(length=5), nullable=False),
    sa.Column('consultation_type', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('price_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_appointments_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('fk_appointments_patient_user_id_users')),
    sa.ForeignKeyConstraint(['service_id'], ['provider_services.id'], name=op.f('fk_appointments_service_id_provider_services')),
    sa.ForeignKeyConstraint(['specialty_slug'], ['specialties.slug'], name=op.f('fk_appointments_specialty_slug_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index('ix_appointments_patient', ['patient_user_id', 'appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_user_id'), ['patient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index('uq_active_appointment_slot', ['doctor_id', 'appointment_date', 'appointment_time'], unique=True, sqlite_where=sa.text("status IN ('REQUESTED','CONFIRMED','RESCHEDULED')"), postgresql_where=sa.text("status IN ('REQUESTED','CONFIRMED','RESCHEDULED')"))

    op.create_table('service_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['provider_services.id'], name=op.f('fk_service_prices_service_id_provider_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_prices'))
    )
    with op.batch_alter_table('service_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_prices_service_id'), ['service_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_prices_service_id'))

    op.drop_table('service_prices')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('uq_active_appointment_slot', sqlite_where=sa.text("status IN ('REQUESTED','CONFIRMED','RESCHEDULED')"), postgresql_where=sa.text("status IN ('REQUESTED','CONFIRMED','RESCHEDULED')"))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_user_id'))
        batch_op.drop_index('ix_appointments_patient')
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_services_specialty_slug'))
        batch_op.drop_index(batch_op.f('ix_provider_services_provider_id'))
        batch_op.drop_index('ix_provider_services_provider')

    op.drop_table('provider_services')
    with op.batch_alter_table('doctor_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_verifications_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_verifications_created_at'))

    op.drop_table('doctor_verifications')
    with op.batch_alter_table('hospital_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_verifications_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_verifications_created_at'))

    op.drop_table('hospital_verifications')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_verification_status'))
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_specialty_slug'))
        batch_op.drop_index(batch_op.f('ix_doctors_pincode'))
        batch_op.drop_index(batch_op.f('ix_doctors_city'))

    op.drop_table('doctors')
    with op.batch_alter_table('provider_specialty_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_specialty_links_specialty_slug'))
        batch_op.drop_index(batch_op.f('ix_provider_specialty_links_provider_id'))

    op.drop_table('provider_specialty_links')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_verification_status'))
        batch_op.drop_index(batch_op.f('ix_hospitals_pincode'))
        batch_op.drop_index(batch_op.f('ix_hospitals_city'))
        batch_op.drop_index(batch_op.f('ix_hospitals_admin_user_id'))

    op.drop_table('hospitals')
    with op.batch_alter_table('service_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_availability_provider_id'))

    op.drop_table('service_availability')
    with op.batch_alter_table('provider_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_blocks_provider')

    op.drop_table('provider_blocks')
    # ### end Alembic commands ###
